baseURL = "https://thehandycio.z1.web.core.windows.net/"
languageCode = "en-us"
title = "The Handy CIO"
theme = ["m10c", "matomo"]
sectionPagesMenu = "main"
custom_js = ["js/custom.js"]

[params]
  author = "Tim Nilimaa-Svärd"
  description = "Just like an ordinary handyman that can do stuff can this CIO do stuff. Sometimes they work."
  avatar = "media/avatar.jpg"
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/timnilimaa"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/timnilimaa"
  [[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/TimNilimaa"

[params.matomo]
url = "https://stats.jag.se"
id = 2

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"
