baseURL = 'http://handycio.com/'
languageCode = 'en-us'
title = 'The Handy CIO'
theme = 'hello-friend-ng'

paginate  = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.

enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = true
disableHugoGeneratorInject = false

[author]
  name = "Tim Nilimaa-Svärd"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Even a paper pusher can make the code compile"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "The Handy CIO"
  keywords = "homepage, blog"
  images = [""]
  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
    ]
[[params.social]]
  name = "twitter"
  url = "https://twitter.com/TimNilimaa"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"
[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Posts"
    url        = "/posts"

[languages]
  [languages.en]
    title = "The Handy CIO"
    subtitle = "Even a paper pusher can make the code compile"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "./update-org-it-strategy.sh"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

