# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        image: [ext-alpine]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
        submodules: true

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
    # Artifact name
        name: public # optional, default is artifact
    # A file, directory or wildcard pattern that describes what to upload
        path: public/
    - name: Deploy
      uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name thehandycio  --auth-mode key -d '$web' -s public/
    - name: logout
      run: |
            az logout
      if: always()
